Drop DATABASE blog;
CREATE DATABASE blog;
USE blog;
CREATE TABLE IF NOT EXISTS `users`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `userName` VARCHAR(20) UNIQUE,
    `countName` VARCHAR(20) NOT NULL UNIQUE,
    `password` VARCHAR(20) NOT NULL,
    `createTime` char(13) NOT NULL,
    `updateTime` char(13) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `essay`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `authorId` INT UNSIGNED,
    `tagName` varchar(100) NOT NULL,
    `title` varchar(100) NOT NULL UNIQUE,
    `content` TEXT NOT NULL,
    `createTime` char(13) NOT NULL,
    `updateTime` char(13) NOT NULL,
    `viewCount` INT DEFAULT 0,
    FOREIGN KEY(`authorId`) REFERENCES users(`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `friendlyLinks`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `tagName` VARCHAR(20) NOT NULL,
    `name` VARCHAR(20) NOT NULL UNIQUE,
    `path` VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `hotKeywords`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `keyword` VARCHAR(100) NOT NULL UNIQUE,
    `searchCount` INT NOT NULL DEFAULT 1
)ENGINE=InnoDB DEFAULT CHARSET=utf8;